name: Build and publish release binaries
on:
  release:
    types: [created]
jobs:
  build-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: |
        go get -u github.com/gobuffalo/packr/v2/packr2
        go get -v -t -d ./...
    - name: Build binaries
      run: |
        export GO111MODULE=on
        packr2
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o ./vrhr-windows-amd64.exe .
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o ./vrhr-darwin-amd64 .
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o ./vrhr-linux-amd64 .
        packr2 clean
    - name: Upload binaries
      uses: skx/github-action-publish-binaries@release-1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'vrhr-*'